# SwiftLint Configuration for MappLock iOS

# Paths to include during linting
included:
  - Sources
  - MappLock
  - MappLockCore
  - MappLockWidget
  - MappLockEnterpriseExtension
  - Tests

# Paths to ignore during linting
excluded:
  - Carthage
  - Pods
  - .build
  - DerivedData
  - .swiftpm

# Enabled rules
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_object_literal
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prefixed_toplevel_constant
  - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strict_fileprivate
  - switch_case_on_newline
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

# Disabled rules
disabled_rules:
  - todo
  - line_length # Handled by function_body_length instead

# Rule configurations
analyzer_rules:
  - explicit_self
  - unused_declaration
  - unused_import

# Line length configuration
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true
  ignores_interpolated_strings: true

# Function body length
function_body_length:
  warning: 50
  error: 100

# Function parameter count
function_parameter_count:
  warning: 6
  error: 8

# Type body length
type_body_length:
  warning: 300
  error: 400

# File length
file_length:
  warning: 500
  error: 800

# Nesting levels
nesting:
  type_level:
    warning: 2
    error: 3
  statement_level:
    warning: 5
    error: 10

# Cyclomatic complexity
cyclomatic_complexity:
  warning: 10
  error: 20

# Identifier name rules
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 60
    error: 80
  excluded:
    - id
    - url
    - uri
    - UIViewController
    - URLSessionDataTask

# Type name rules
type_name:
  min_length:
    warning: 3
    error: 1
  max_length:
    warning: 50
    error: 80

# Large tuple
large_tuple:
  warning: 3
  error: 4

# Custom rules
custom_rules:
  # Prefer NSLocalizedString over hardcoded strings in user-facing text
  hardcoded_string:
    name: "Hardcoded String"
    regex: '(Text|Label|Button|Alert)\("(?!.*NSLocalizedString).*"'
    message: "Use NSLocalizedString for user-facing text"
    severity: warning

  # Ensure proper error handling
  force_try:
    name: "Force Try"
    regex: 'try!'
    message: "Prefer proper error handling over force try"
    severity: error

  # Ensure proper logging
  print_usage:
    name: "Print Usage"
    regex: 'print\('
    message: "Use Logger instead of print for production code"
    severity: warning
    excluded: ".*Test.*"

  # Ensure proper async/await usage
  completion_handler:
    name: "Completion Handler"
    regex: '@escaping.*->'
    message: "Consider using async/await instead of completion handlers"
    severity: warning

# Reporter type
reporter: "xcode"

# File header template
file_header:
  required_pattern: |
                    \/\/ .*\.swift.*
                    \/\/ MappLock.*
                    .*
                    \/\/ Copyright © \d{4} MappLock\. All rights reserved\.

# Trailing whitespace
trailing_whitespace:
  ignores_empty_lines: false
  ignores_comments: true

# Trailing comma
trailing_comma:
  mandatory_comma: false

# Vertical whitespace
vertical_whitespace:
  max_empty_lines: 2

# Empty parentheses with trailing closure
empty_parentheses_with_trailing_closure: true

# Multiline arguments
multiline_arguments:
  first_argument_location: next_line
  only_enforce_after_first_closure_on_first_line: true

# Multiline parameters
multiline_parameters:
  allows_single_line: true

# Closure parameter position
closure_parameter_position:
  severity: warning

# Control statement
control_statement:
  severity: error

# Comma inheritance
comma: error

# Colon spacing
colon:
  flexible_right_spacing: false
  apply_to_dictionaries: true

# Opening brace spacing
opening_brace: error

# Return arrow whitespace
return_arrow_whitespace: error

# Statement position
statement_position:
  severity: error

# Switch case alignment
switch_case_alignment:
  indented_cases: false

# Redundant discardable let
redundant_discardable_let: error

# Redundant optional binding
redundant_optional_binding: error

# Explicit enum raw value
explicit_enum_raw_value:
  severity: warning

# Explicit top level ACL
explicit_top_level_acl:
  severity: warning

# Extension access modifier
extension_access_modifier:
  severity: error

# Generic type name
generic_type_name:
  min_length:
    warning: 1
  max_length:
    warning: 20